### ISSUE TITLE
make size selection not scrict

### ISSUE THREAD

**Issue by rom1504** [iejMac/video2dataset#40]

**Comment by iejMac** [comment]
is this for allowing lower resolution and sizing up?

**Comment by rom1504** [comment]
Yes

**Comment by iejMac** [comment]
@rom1504 couldn't find any way of specifying "closest format according to resolution" but we could manually do it in python by finding:
- worst format >= target_resolution
- best format <= target_resolution
and comparing which is closer using metadata in the return formats

problem with this is not sure if we want to take on the extra overhead of playing with formats again. The speedup we recently got was from not playing with formats and just trusting yt-dlp to give us the best format. To that end I suggest 2 options, would like to hear some thoughts:
1. we try the thing I suggested earlier, test it, etc.
2. we implement resolution subsampler and use that on the output of data reader to get exact resolution we want and move this to v1

**Comment by iejMac** [comment]
ChatGPT suggests using max_resolution with height and width and then combine with | best

**Comment by iejMac** [comment]
summarizing my thoughts on this again:

we need to make it so that users have more choices about the output dimensionality than just - what YT has or EXACT video_size x video_size. To do this we need to implement the following functionality:
- try to pick the smallest video larger than the video_size
- if that's not available and all videos are smaller than take the largest video, smaller than video_size
- if some resize mode is "pad", pad the video to video_size x video_size
- otherwise just save the smaller version
